#!/usr/bin/env bash
# Comment


s_domains=( www lb-01 web-01 web-02 )
domain=$1
if [ $# -eq 2 ]; then
	subd=$2
	echo -n "The subdomain $subd is a "
	dig "$subd"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'

else
	for i in "${s_domains[@]}"; do
		subdomain=$i
		echo -n "The sudomain $subdomain is a "
		dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'
	done
fi
