#!/usr/bin/env bash
# Copy file to server

file_path="$1"
ip_address="$2"
user="$3"
key_path="$4"

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" "$user"@"$ip_address":~/
fi