#!/usr/bin/env bash
#Script to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
