#!/usr/bin/env bash
# Comment
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "35i\\n\tadd_header X-Served-By $HOSTNAME;\n"\
	/etc/nginx/sites-available/default
sudo service nginx restart
