#!/usr/bin/env bash
# Comment
sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haprox_backup.cfg

# Enable usage of an init script
sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy
sudo sed -i "$ a\ \nfrontend http_front\n\t bind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 1300-web-01 35.227.77.93:80 check\n\tserver 1300-web-02 35.175.171.90:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
