#!/usr/bin/env bash
#This comment
_term()
{
	echo "I hate the kill command"
	rm '/var/run/holbertonscript.pid'
	exit
}
_int()
{
	echo "Y U no love me?!"
}
_exit()
{
	rm '/var/run/holbertonscript.pid'
	exit
}
trap _term SIGTERM
trap _int SIGINT
trap _exit SIGQUIT

echo $$ > /var/run/holbertonscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
