#!/usr/bin/env bash
#This is a comment
while IFS=: read -r usname passwd uid gid uidinf home shell
do
	echo "The user $usname is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $uidinf"
done < /etc/passwd
