#!/usr/bin/env bash
# Tests file detail
ftest="./holbertonschool"
if [ -e $ftest ]
then
	echo "holbertonschool file exists"
	if [ -s $ftest ]
	then
		echo "holbertonschool file is not empty"
		if [ -f $ftest ]
		then
			echo "holbertonschool is a regular file"
		fi
	else
		echo "holbertonschool file is empty"
		if [ -f $ftest ]
		then
			echo "holbertonschool is a regular file"
		fi
	fi
else
	echo "holbertonschool file does not exist"
fi

